include:
  - package:flutter_lints/flutter.yaml

analyzer:

  exclude:
    - build/**
plugins:
  clean_arch_lint:
    path: ../
    diagnostics:
      no_data_dependencies: true
      domain_only_depends_on_itself: true
      no_screens_dependencies: true


