include:
  - package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    clean_arch_lint:
      paths: C:\\Users\\saulo\\repo\\clean_arch_lint
      diagnostics:
        presentation_no_data: true
        teste_meu: true
