include:
  - package:flutter_lints/flutter.yaml

analyzer:

  exclude:
    - build/**
plugins:
  clean_arch_lint:
    path: ../
    diagnostics:
      presentation_no_data: error # enable to see the error, default is warning
      teste_meu: false # disable to not see the warning. Default is true.



